import type { Metadata } from "next";
import {
	Cormorant_Garamond,
	Geist,
	Geist_Mono,
	IBM_Plex_Mono,
	Urbanist,
} from "next/font/google";

import "./globals.css";

import { CustomCursor } from "@/components/ui/cursor";
import { Preloader } from "@/components/layouts/preloader";
import { GlobalAlert } from "@/components/layouts/alert";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const cormorant = Cormorant_Garamond({
	subsets: ["latin", "cyrillic"],
	weight: ["400", "500", "600", "700"],
	style: ["normal", "italic"],
	variable: "--font-cormorant",
});

const urbanist = Urbanist({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700", "800", "900"],
	style: ["normal", "italic"],
	variable: "--font-urbanist",
});

const ibmPlexMono = IBM_Plex_Mono({
	subsets: ["latin", "cyrillic"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-ibmplexmono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${ibmPlexMono.variable} ${urbanist.variable} ${geistSans.variable} ${cormorant.variable} ${geistMono.variable} antialiased`}>
				<Preloader />

				<CustomCursor />
				<GlobalAlert />
				{children}
			</body>
		</html>
	);
}
